apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myntra-ingress
  annotations: 
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-0ed24225629f7ab13,subnet-0f9b9be61d2e14a0e
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myntra-service  # Updated to use myntra-service
                port:
                  number: 80